deck = [
    # Red Cards
    {'color': 'Red', 'type': '0'},
    {'color': 'Red', 'type': '0'},
    {'color': 'Red', 'type': '1'},
    {'color': 'Red', 'type': '1'},
    {'color': 'Red', 'type': '2'},
    {'color': 'Red', 'type': '2'},
    {'color': 'Red', 'type': '3'},
    {'color': 'Red', 'type': '3'},
    {'color': 'Red', 'type': '4'},
    {'color': 'Red', 'type': '4'},
    {'color': 'Red', 'type': '5'},
    {'color': 'Red', 'type': '5'},
    {'color': 'Red', 'type': '6'},
    {'color': 'Red', 'type': '6'},
    {'color': 'Red', 'type': '7'},
    {'color': 'Red', 'type': '7'},
    {'color': 'Red', 'type': '8'},
    {'color': 'Red', 'type': '8'},
    {'color': 'Red', 'type': '9'},
    {'color': 'Red', 'type': '9'},
    {'color': 'Red', 'type': 'Skip'},
    {'color': 'Red', 'type': 'Skip'},
    {'color': 'Red', 'type': 'Skip'},
    {'color': 'Red', 'type': 'Skip All'},
    {'color': 'Red', 'type': 'Skip All'},
    {'color': 'Red', 'type': 'Reverse'},
    {'color': 'Red', 'type': 'Reverse'},
    {'color': 'Red', 'type': 'Reverse'},
    {'color': 'Red', 'type': 'Draw Two'},
    {'color': 'Red', 'type': 'Draw Two'},
    {'color': 'Red', 'type': 'Draw Two'},
    {'color': 'Red', 'type': 'Draw Four'},
    {'color': 'Red', 'type': 'Draw Four'},
    {'color': 'Red', 'type': 'Discard All of Color'},
    {'color': 'Red', 'type': 'Discard All of Color'},
    {'color': 'Red', 'type': 'Discard All of Color'},
    # Aditional Cards from Extension Pack
    # {'color': 'Red', 'type': '10's Play Again'},
    # {'color': 'Red', 'type': '10's Play Again'}

    # Green Cards
    {'color': 'Green', 'type': '0'},
    {'color': 'Green', 'type': '0'},
    {'color': 'Green', 'type': '1'},
    {'color': 'Green', 'type': '1'},
    {'color': 'Green', 'type': '2'},
    {'color': 'Green', 'type': '2'},
    {'color': 'Green', 'type': '3'},
    {'color': 'Green', 'type': '3'},
    {'color': 'Green', 'type': '4'},
    {'color': 'Green', 'type': '4'},
    {'color': 'Green', 'type': '5'},
    {'color': 'Green', 'type': '5'},
    {'color': 'Green', 'type': '6'},
    {'color': 'Green', 'type': '6'},
    {'color': 'Green', 'type': '7'},
    {'color': 'Green', 'type': '7'},
    {'color': 'Green', 'type': '8'},
    {'color': 'Green', 'type': '8'},
    {'color': 'Green', 'type': '9'},
    {'color': 'Green', 'type': '9'},
    {'color': 'Green', 'type': 'Skip'},
    {'color': 'Green', 'type': 'Skip'},
    {'color': 'Green', 'type': 'Skip'},
    {'color': 'Green', 'type': 'Skip All'},
    {'color': 'Green', 'type': 'Skip All'},
    {'color': 'Green', 'type': 'Reverse'},
    {'color': 'Green', 'type': 'Reverse'},
    {'color': 'Green', 'type': 'Reverse'},
    {'color': 'Green', 'type': 'Draw Two'},
    {'color': 'Green', 'type': 'Draw Two'},
    {'color': 'Green', 'type': 'Draw Two'},
    {'color': 'Green', 'type': 'Draw Four'},
    {'color': 'Green', 'type': 'Draw Four'},
    {'color': 'Green', 'type': 'Discard All of Color'},
    {'color': 'Green', 'type': 'Discard All of Color'},
    {'color': 'Green', 'type': 'Discard All of Color'},
    # Additional Cards from Extension Pack
    # {'color': 'Green', 'type': '10's Play Again'},
    # {'color': 'Green', 'type': '10's Play Again'}

    # Blue Cards
    {'color': 'Blue', 'type': '0'},
    {'color': 'Blue', 'type': '0'},
    {'color': 'Blue', 'type': '1'},
    {'color': 'Blue', 'type': '1'},
    {'color': 'Blue', 'type': '2'},
    {'color': 'Blue', 'type': '2'},
    {'color': 'Blue', 'type': '3'},
    {'color': 'Blue', 'type': '3'},
    {'color': 'Blue', 'type': '4'},
    {'color': 'Blue', 'type': '4'},
    {'color': 'Blue', 'type': '5'},
    {'color': 'Blue', 'type': '5'},
    {'color': 'Blue', 'type': '6'},
    {'color': 'Blue', 'type': '6'},
    {'color': 'Blue', 'type': '7'},
    {'color': 'Blue', 'type': '7'},
    {'color': 'Blue', 'type': '8'},
    {'color': 'Blue', 'type': '8'},
    {'color': 'Blue', 'type': '9'},
    {'color': 'Blue', 'type': '9'},
    {'color': 'Blue', 'type': 'Skip'},
    {'color': 'Blue', 'type': 'Skip'},
    {'color': 'Blue', 'type': 'Skip'},
    {'color': 'Blue', 'type': 'Skip All'},
    {'color': 'Blue', 'type': 'Skip All'},
    {'color': 'Blue', 'type': 'Reverse'},
    {'color': 'Blue', 'type': 'Reverse'},
    {'color': 'Blue', 'type': 'Reverse'},
    {'color': 'Blue', 'type': 'Draw Two'},
    {'color': 'Blue', 'type': 'Draw Two'},
    {'color': 'Blue', 'type': 'Draw Two'},
    {'color': 'Blue', 'type': 'Draw Four'},
    {'color': 'Blue', 'type': 'Draw Four'},
    {'color': 'Blue', 'type': 'Discard All of Color'},
    {'color': 'Blue', 'type': 'Discard All of Color'},
    {'color': 'Blue', 'type': 'Discard All of Color'},
    # Additional Cards from Extension Pack
    # {'color': 'Blue', 'type': '10's Play Again'},
    # {'color': 'Blue', 'type': '10's Play Again'}

    # Yellow Cards
    {'color': 'Yellow', 'type': '0'},
    {'color': 'Yellow', 'type': '0'},
    {'color': 'Yellow', 'type': '1'},
    {'color': 'Yellow', 'type': '1'},
    {'color': 'Yellow', 'type': '2'},
    {'color': 'Yellow', 'type': '2'},
    {'color': 'Yellow', 'type': '3'},
    {'color': 'Yellow', 'type': '3'},
    {'color': 'Yellow', 'type': '4'},
    {'color': 'Yellow', 'type': '4'},
    {'color': 'Yellow', 'type': '5'},
    {'color': 'Yellow', 'type': '5'},
    {'color': 'Yellow', 'type': '6'},
    {'color': 'Yellow', 'type': '6'},
    {'color': 'Yellow', 'type': '7'},
    {'color': 'Yellow', 'type': '7'},
    {'color': 'Yellow', 'type': '8'},
    {'color': 'Yellow', 'type': '8'},
    {'color': 'Yellow', 'type': '9'},
    {'color': 'Yellow', 'type': '9'},
    {'color': 'Yellow', 'type': 'Skip'},
    {'color': 'Yellow', 'type': 'Skip'},
    {'color': 'Yellow', 'type': 'Skip'},
    {'color': 'Yellow', 'type': 'Skip All'},
    {'color': 'Yellow', 'type': 'Skip All'},
    {'color': 'Yellow', 'type': 'Reverse'},
    {'color': 'Yellow', 'type': 'Reverse'},
    {'color': 'Yellow', 'type': 'Reverse'},
    {'color': 'Yellow', 'type': 'Draw Two'},
    {'color': 'Yellow', 'type': 'Draw Two'},
    {'color': 'Yellow', 'type': 'Draw Two'},
    {'color': 'Yellow', 'type': 'Draw Four'},
    {'color': 'Yellow', 'type': 'Draw Four'},
    {'color': 'Yellow', 'type': 'Discard All of Color'},
    {'color': 'Yellow', 'type': 'Discard All of Color'},
    {'color': 'Yellow', 'type': 'Discard All of Color'},
    # Additional Cards from Extension Pack
    # {'color': 'Yellow', 'type': '10's Play Again'},
    # {'color': 'Yellow', 'type': '10's Play Again'}

    # Wild Cards
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Reverse Draw Four'},
    {'color': 'Wild', 'type': 'Draw Six'},
    {'color': 'Wild', 'type': 'Draw Six'},
    {'color': 'Wild', 'type': 'Draw Six'},
    {'color': 'Wild', 'type': 'Draw Six'},
    {'color': 'Wild', 'type': 'Draw Ten'},
    {'color': 'Wild', 'type': 'Draw Ten'},
    {'color': 'Wild', 'type': 'Draw Ten'},
    {'color': 'Wild', 'type': 'Draw Ten'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    {'color': 'Wild', 'type': 'Color Roulette'},
    # Additional Cards from Extension Pack
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Discard All'},
    # {'color': 'Wild', 'type': 'Wild Reverse Draw Eight'},
    # {'color': 'Wild', 'type': 'Wild Reverse Draw Eight'},
    # {'color': 'Wild', 'type': 'Wild Reverse Draw Eight'},
    # {'color': 'Wild', 'type': 'Wild Reverse Draw Eight'},
    # {'color': 'Wild', 'type': 'Wild Final Attack'},
    # {'color': 'Wild', 'type': 'Wild Final Attack'},
    # {'color': 'Wild', 'type': 'Wild Sudden Death'},
    # {'color': 'Wild', 'type': 'Wild Sudden Death'}

]